server:
  port: 10086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka/
  server:
    eviction-interval-timer-in-ms: 10000 # 每隔10秒对失效的服务进行剔除，默认值为 60秒
    enable-self-preservation: false # 关闭自我保护模式，默认值为 true