server:
  port: 10010

zuul:
  routes:
    service-provider: /provider/**
  prefix: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/, http://localhost:10087/eureka/
