server:
  port: 10010

zuul:
  routes:
    service-consumer: /consumer/**
  prefix: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
    registry-fetch-interval-seconds: 5
